### PR TITLE
Fix unsoundness issues #106 and #107

### LINKED ISSUE #106: Soundness hole: transmuting item type using `yield` in a nested `async` block awaited in the wrong place
It seems (me looking at macro expansions) that `yield` usage in an `async {}` block is not expanded by this macro, and that’s good - in principle - because it can be unsound to await that in the wrong place with the way that thread-locals are used.

However, this is a syntactic analysis, and `yield` in macros are expanded, so well, that can be a problem if a macro introduces an `async` block:
```rs
use async_stream::stream;
use futures::StreamExt;

use std::pin::pin;

macro_rules! asynk {
    ($e:expr) => {
        async { $e }
    };
}

#[tokio::main]

async fn main() {
    pin!(stream! {
        let yield_42 = asynk!(yield 42_usize);
        let s = stream! {
            yield Box::new(12345);
            yield_42.await; // yield 42 -- wait that's not a Box!?
        };
        for await (n, i) in s.enumerate() {
            println!("Item at index {n}:\n    {i}");
            // Item at index 0:
            //     12345
            // Item at index 1:
            // Segmentation fault
        }
    })
    .next()
    .await;
}
```
([run on rustexplorer.com](https://www.rustexplorer.com/b#LyoKW2RlcGVuZGVuY2llc10KYXN5bmMtc3RyZWFtID0gIjAuMyIKZnV0dXJlcyA9ICIwLjMiCnRva2lvID0geyB2ZXJzaW9uID0gIjEuMzciLCBmZWF0dXJlcyA9IFsibWFjcm9zIiwgInJ0LW11bHRpLXRocmVhZCJdIH0KKi8KCnVzZSBhc3luY19zdHJlYW06OnN0cmVhbTsKdXNlIGZ1dHVyZXM6OlN0cmVhbUV4dDsKCnVzZSBzdGQ6OnBpbjo6cGluOwoKbWFjcm9fcnVsZXMhIGFzeW5rIHsKICAgICgkZTpleHByKSA9PiB7CiAgICAgICAgYXN5bmMgeyAkZSB9CiAgICB9Owp9CgojW3Rva2lvOjptYWluXQoKYXN5bmMgZm4gbWFpbigpIHsKICAgIHBpbiEoc3RyZWFtISB7CiAgICAgICAgbGV0IHlpZWxkXzQyID0gYXN5bmshKHlpZWxkIDQyX3VzaXplKTsKICAgICAgICBsZXQgcyA9IHN0cmVhbSEgewogICAgICAgICAgICB5aWVsZCBCb3g6Om5ldygxMjM0NSk7CiAgICAgICAgICAgIHlpZWxkXzQyLmF3YWl0OyAvLyB5aWVsZCA0MiAtLSB3YWl0IHRoYXQncyBub3QgYSBCb3ghPwogICAgICAgIH07CiAgICAgICAgZm9yIGF3YWl0IChuLCBpKSBpbiBzLmVudW1lcmF0ZSgpIHsKICAgICAgICAgICAgcHJpbnRsbiEoIkl0ZW0gYXQgaW5kZXgge259OlxuICAgIHtpfSIpOwogICAgICAgICAgICAvLyBJdGVtIGF0IGluZGV4IDA6CiAgICAgICAgICAgIC8vICAgICAxMjM0NQogICAgICAgICAgICAvLyBJdGVtIGF0IGluZGV4IDE6CiAgICAgICAgICAgIC8vIFNlZ21lbnRhdGlvbiBmYXVsdAogICAgICAgIH0KICAgIH0pCiAgICAubmV4dCgpCiAgICAuYXdhaXQ7Cn0KCg==))

This kind of abuse could be better prevented with a trick I came up with in https://github.com/dureuill/nolife/issues/8#issuecomment-1975217153, the idea is to make the whole `stream!` invocation create a labelled block, and have `yield` include a `if false` guarded `break` from the same label; this will successfully prevent compilation in case the `yield` is anywhere where control-flow cannot directly jump back to the top-level of `stream!` (which should correspond to anywhere where the `.await` of the `yield` expansion does not correspond to the outer `async` block from the `stream!` expansion), hence preventing accidental use of `yield` in a nested `async` block.

_(For `nolife`, the macro involved a `macro_rules` macro, where the default hygiene rules would successfully prevent the labels not matching up properly; I don't quite remember off the top of my head how far support for doing the same in proc-macros is nowadays.)_

### LINKED ISSUE #107: Soundness hole: Use-after-free through mismatching lifetimes of stream item and yielded type
Soundness hole: Use-after-free through mismatching lifetimes of stream item and yielded type

This is almost trivially simple to run into. Just yield something that's shorter-lived than what the place using the stream requires, and … _it just compiles_.

(The only “trick” to avoiding compiler errors with this is that one needs to have the stream itself must not be kept alive for too long; i.e. significantly shorter than the items one gets from it.) 

```rs
use async_stream::stream;
use futures::StreamExt;

use std::pin::pin;

#[tokio::main]
async fn main() {
    let mut outer = vec![];
    {
        let v = vec![0; 10];
        let v_ref = &v;
        let mut s = pin!(stream! {
            for x in v_ref {
                yield x
            }
        });
        while let Some(x) = s.next().await {
            outer.push(x);
        }
    };
    // use-after-free
    println!("{outer:?}"); // […garbage allocator internals…, 0, 0, 0]
}
```
([run on rustexplorer.com](https://www.rustexplorer.com/b#LyoKW2RlcGVuZGVuY2llc10KYXN5bmMtc3RyZWFtID0gIjAuMy41IgpmdXR1cmVzID0gIjAuMy4zMCIKdG9raW8gPSB7IHZlcnNpb24gPSAiMS4zNy4wIiwgZmVhdHVyZXMgPSBbIm1hY3JvcyIsICJydC1tdWx0aS10aHJlYWQiXSB9CiovCgp1c2UgYXN5bmNfc3RyZWFtOjpzdHJlYW07CnVzZSBmdXR1cmVzOjpTdHJlYW1FeHQ7Cgp1c2Ugc3RkOjpwaW46OnBpbjsKCiNbdG9raW86Om1haW5dCmFzeW5jIGZuIG1haW4oKSB7CiAgICBsZXQgbXV0IG91dGVyID0gdmVjIVtdOwogICAgewogICAgICAgIGxldCB2ID0gdmVjIVswOyAxMF07CiAgICAgICAgbGV0IHZfcmVmID0gJnY7CiAgICAgICAgbGV0IG11dCBzID0gcGluIShzdHJlYW0hIHsKICAgICAgICAgICAgZm9yIHggaW4gdl9yZWYgewogICAgICAgICAgICAgICAgeWllbGQgeAogICAgICAgICAgICB9CiAgICAgICAgfSk7CiAgICAgICAgd2hpbGUgbGV0IFNvbWUoeCkgPSBzLm5leHQoKS5hd2FpdCB7CiAgICAgICAgICAgIG91dGVyLnB1c2goeCk7CiAgICAgICAgfQogICAgfTsKICAgIC8vIHVzZS1hZnRlci1mcmVlCiAgICBwcmludGxuISgie291dGVyOj99Iik7IC8vIFvigKZnYXJiYWdlIGFsbG9jYXRvciBpbnRlcm5hbHPigKYsIDAsIDAsIDBdCn0=))

The relevant problem here is likely the covariance of the [`Sender`](https://docs.rs/async-stream/0.3.5/src/async_stream/yielder.rs.html#8-11) type; I'm not 100% sure I understand what part of the expanded code currently allows for the corresponding unsound coercion to happen, nor do I know whether this was always accepted by the compiler, but even before that, the wrong covariance would've been not future-proof.

---

In my experience, this `Sender`/`Receiver` helper type pair that's supposed to ensure the `yield`ed type is matching the item type might as well be unified into a single type, anyway. Especially after #106 is fixed, there's not really any point in involving a mutable borrow into this, it could simply be a simple `Copy` marker type that serves both roles of the current `__yield_tx` and `__yield_rx` (and `.send` method gets a by-value `fn …(self, …)` argument). The `PhantomData` inside would need to be invariant then, e.g. via `PhantomData<fn(T) -> T>`.

A minimal change on the other hand would be to just make the `Sender<T>` invariant or contravariant in `<T>`. With such a fix, we can gain the desired compilation error:
```
error[E0597]: `v` does not live long enough
  --> src/main.rs:11:21
   |
10 |         let v = vec![0; 10];
   |             - binding `v` declared here
11 |         let v_ref = &v;
   |                     ^^ borrowed value does not live long enough
...
20 |     };
   |     - `v` dropped here while still borrowed
21 |     println!("{outer:?}");
   |               --------- borrow later used here
```

### PR DESCRIPTION
**Pull request by aumetra**
This PR fixes the unsoundness reported in #106 and #107

cc @steffahn (for checking the fixes, whether they are actually correct)

Closes #106 
Closes #107

### CODE REVIEW

**Comment by aumetra** [comment]
The CI failures seem unrelated. Probably UI updates in the Rust compiler.
Should I fix them in this PR or separately?

**Comment by taiki-e** [comment]
Thanks for the PR! 

- CI failure has been fixed in #111.
- Could you add regression tests for these unsoundness? (e.g., ui test to make sure that problematic cases are no longer compiled)

**Comment by aumetra** [comment]
Of course, will do

File: async-stream-impl/src/lib.rs [hunk 1]
```diff
@@ -120,10 +120,19 @@ impl VisitMut for Scrub<'_> {
...
                 } else {
-                    syn::parse_quote! { __yield_tx.send(#value_expr).await }
+                    quote! { __yield_tx.send(#value_expr).await }
+                };
+                *i = syn::parse_quote! {
+                    {
+                        #[allow(unreachable_code)]
+                        if false {
+                            break 'check_stream_scope (loop {});
+                        }
```
Comment (taiki-e) [inline async-stream-impl/src/lib.rs:133]: Perhaps this can still be bypassed by defining a block labeled `'check_stream_scope` in the async block.

That said, if we rename the label to something that clearly indicates that it is a async-stream's private API (something like `'__async_stream_private_check_scope`), that would actually be sufficient, since only “users who explicitly abuse private APIs” would be affected.

File: async-stream-impl/src/lib.rs [hunk 2]
```diff
@@ -225,8 +234,10 @@ pub fn stream_inner(input: TokenStream) -> TokenStream {
     quote!({
         let (mut __yield_tx, __yield_rx) = unsafe { #crate_path::__private::yielder::pair() };
         #crate_path::__private::AsyncStream::new(__yield_rx, async move {
-            #dummy_yield
-            #(#stmts)*
+            'check_stream_scope: {
```
Comment (taiki-e) [inline async-stream-impl/src/lib.rs:237]: The label-break-value was stabilized in Rust 1.65 (https://github.com/rust-lang/rust/issues/48594), so this will increase the MSRV. This is okay since it is for soundness.

Could you update the documentation and rust-version fields?

https://github.com/tokio-rs/async-stream/blob/0588ec1e961e033ac0a84d30e50c86bf1029ddbe/async-stream/README.md?plain=1#L155
https://github.com/tokio-rs/async-stream/blob/0588ec1e961e033ac0a84d30e50c86bf1029ddbe/async-stream/Cargo.toml#L8
https://github.com/tokio-rs/async-stream/blob/0588ec1e961e033ac0a84d30e50c86bf1029ddbe/async-stream-impl/Cargo.toml#L5

File: async-stream/tests/ui/unsoundness_issue_106.rs [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+use std::pin::pin;
+
+macro_rules! asynk {
+    ($e:expr) => {
+        async { $e }
+    };
+}
+
+#[tokio::main]
+
```
Comment (taiki-e) [inline async-stream/tests/ui/unsoundness_issue_106.rs:13]:
```suggestion
```

**Review by taiki-e — CHANGES_REQUESTED** [review]
Thanks! LGTM aside from a few nits.

**Comment by taiki-e** [comment]
It seems that the MSRV bump triggered a new clippy warning. Could you address that as well?

```
error: initializer for `thread_local` value can be made `const`
  --> async-stream/src/yielder.rs:37:45
   |
37 | thread_local!(static STORE: Cell<*mut ()> = Cell::new(ptr::null_mut()));
   |                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^ help: replace with: `const { Cell::new(ptr::null_mut()) }`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#missing_const_for_thread_local
   = note: `-D clippy::missing-const-for-thread-local` implied by `-D warnings`
   = help: to override `-D warnings` add `#[allow(clippy::missing_const_for_thread_local)]`
```

**Comment by taiki-e** [comment]
inline const in thread_local is special and is available since Rust 1.59: https://github.com/rust-lang/rust/pull/91355

**Comment by aumetra** [comment]
Ah, interesting. Didn't know. Fixing it.

**Review by taiki-e — APPROVED** [review]

**Comment by taiki-e** [comment]
Published in 0.3.6.
